# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-23 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='foodpart',
            name='food_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.FoodTime'),
        ),
        migrations.AddField(
            model_name='food',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.FoodPart'),
        ),
    ]
