# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-23 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodpart',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='foodpart',
            unique_together=set([('name', 'food_time')]),
        ),
    ]
