# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-23 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20161223_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='food',
            unique_together=set([('name', 'part')]),
        ),
    ]
